pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1' 
        DYNAMO_TABLE = 'nyk_usm_config_pp1'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/yash-agrawal1/activate_test_user'
            }
        }
        stage('Read JSON and Update Items in DynamoDB') {
            steps {
                script {
                    def jsonString = readFile("config_values.txt").trim()

                    // Update DynamoDB
                    sh """
                        aws dynamodb update-item \
                            --table-name ${env.DYNAMO_TABLE} \
                            --key '{"config_name": {"S": "test_users"}}' \
                            --update-expression "ADD config_value :newCustomerIds" \
                            --expression-attribute-values '{":newCustomerIds": ${jsonString}}' \
                            --region ${env.AWS_REGION}
                    """
                }
            }
        }
    }
}